network:
    # otype: CutlassMLP
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: None
    n_neurons: 128
    n_hidden_layers: 6


encoding:
    otype: HashGrid
    type: Hash
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 16
    per_level_scale: 2.0
    n_frequencies: 16


optim:
    epochs: 1
    loss: L2
    milestones: [1, 2, 3, 4]
    gamma: 0.5
    batchsize: 512
    samples_per_ray: 192
    learning_rate: 1e-3
    pixel_importance_sampling: false
    seed: 1337
    factor: 1.0
    resume_training: true
    checkpoint: /home/multari/temnerf/tests_volume/zyx/nerf_volume.pt
    # checkpoint: /home/multari/temnerf/nerf_volume.pt
    # checkpoint: /home/multari/temnerf/outputs/2024-07-24/pretrained_walnut_128/checkpoints/nerf_model_4.pt
data:
    # dataset: walnut
    dataset: tem
    transforms_file: transforms
    img_size: 128
    n_images: 40
    dist: 1/np.sqrt(2)
    noise_level: 0
    # images_path: data/Au_Ag/Serie_3_ali.tif
    # angles_path: data/Au_Ag/TiltAngle_ali.txt

    # images_path: data/benchmark/shepp_logan_180_8bit.tiff
    # angles_path: data/benchmark/shepp_logan_180.txt

    images_path: data/benchmark/au_ag_sirt_180_8bit.tiff
    angles_path: data/benchmark/au_ag_sirt_180.txt
    ground_truth_path: data/benchmark/au_ag_sirt_128.npy

    # images_path: data/benchmark/tube_180_8bit.tiff
    # angles_path: data/benchmark/tube_180.txt
    # ground_truth_path: data/benchmark/tube_256.npy

    # images_path: data/benchmark/sphere_180_8bit.tiff
    # angles_path: data/benchmark/sphere_180.txt
    # ground_truth_path: data/benchmark/sphere_256.npy

output:
    images: true
    slices: true
    volume: true
    samples_per_ray: 192
    slice_resolution: 128
    rays_per_pixel: 16
    interval: 10
    intermediate_slices: false

hardware:
    train: cuda
    test: cuda

# Hydra settings
hydra:
    job:
        chdir: false # If true, sets the current run directory as the working directory (e.g output/2024-05-27/16-55-10/)
