network:
    input_size: 512    # Input size for network
    output_size: 1
    depth: 8         # Depth of MLP layers
    width: 256  

encoding:
    embedding: gauss
    scale: 4
    embedding_size: 256
    coordinates_size: 3


optim:
    training_epochs: 20
    loss: L2
    milestones: [4, 8, 12]
    gamma: 0.5
    batchsize: 1024
    samples_per_ray: 192
    learning_rate: 0.001
    pixel_importance_sampling: false
    seed: 0
    # checkpoint: outputs/2024-06-21/17-58-25/checkpoints/nerf_model_4.pt
    checkpoint: /home/multari/temnerf/outputs/2024-06-24/08-52-30/checkpoints/nerf_model_18.pt

data:
    img_size: 128
    n_images: 75
    images_path: data/Au_Ag/Serie_3_ali.tif
    angles_path: data/Au_Ag/TiltAngle_ali.txt

output:
    images: true
    slices: true
    samples_per_ray: 192
    slice_resolution: 512
    rays_per_pixel: 16
    interval: 10
    intermediate_slices: false

hardware:
    train: cuda
    test: cuda

# Hydra settings
hydra:
    job:
        chdir: false # If true, sets the current run directory as the working directory (e.g output/2024-05-27/16-55-10/)
