network:
    # otype: CutlassMLP
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: None
    n_neurons: 128
    n_hidden_layers: 8


encoding:
    otype: HashGrid
    type: Hash
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 17
    base_resolution: 16
    per_level_scale: 1.5
    interpolation: Linear
    n_frequencies: 16
    n_bins: 16


optim:
    training_epochs: 10
    loss: L2
    milestones: [2, 4, 8, 10]
    gamma: 0.5
    batchsize: 2048
    samples_per_ray: 192
    learning_rate: 0.0001 
    pixel_importance_sampling: false
    seed: 0
    # checkpoint: /home/multari/temnerf/outputs/2024-07-03/proj20_batch1024_nerfoutX255_gtUINT8/checkpoints/nerf_model_19.pt
    # checkpoint: /home/multari/temnerf/nerf_model_0.pt
data:
    # dataset: walnut
    dataset: au_ag
    transforms_file: transforms
    img_size: 128
    n_images: 75
    noise_level: 0
    images_path: data/Au_Ag/Serie_3_ali.tif
    angles_path: data/Au_Ag/TiltAngle_ali.txt

output:
    images: true
    slices: true
    volume: false
    samples_per_ray: 192
    slice_resolution: 1024
    rays_per_pixel: 16
    interval: 10
    intermediate_slices: false

hardware:
    train: cuda
    test: cuda

# Hydra settings
hydra:
    job:
        chdir: false # If true, sets the current run directory as the working directory (e.g output/2024-05-27/16-55-10/)
