network:
    # otype: CutlassMLP
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: ReLU
    n_neurons: 128
    n_hidden_layers: 4


encoding:
    otype: HashGrid
    type: Hash
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 8
    per_level_scale: 2.0
    n_frequencies: 16


optim:
    epochs: 1
    loss: L2
    milestones: [1, 2, 3]
    gamma: 0.5
    batchsize: 256
    samples_per_ray: 192
    learning_rate: 1e-3
    pixel_importance_sampling: false
    seed: 0
data:
    # dataset: walnut
    dataset: au_ag
    transforms_file: transforms
    img_size: 128
    n_images: 40
    noise_level: 0
    # images_path: data/Au_Ag/Serie_3_ali.tif
    # angles_path: data/Au_Ag/TiltAngle_ali.txt
    # images_path: data/shepp_projections/shepp_projection_512_120.tiff
    # images_path: data/shepp_projections/shepp_projections_512_120_8bit.tiff
    # angles_path: data/shepp_projections/angles_120.txt
    images_path: data/benchmark/au_ag_sirt_180_8bit.tiff
    angles_path: data/benchmark/au_ag_sirt_180.txt

output:
    images: true
    slices: true
    volume: False
    samples_per_ray: 192
    slice_resolution: 128
    rays_per_pixel: 16
    interval: 10
    intermediate_slices: false

hardware:
    train: cuda
    test: cuda

# Hydra settings
hydra:
    job:
        chdir: false # If true, sets the current run directory as the working directory (e.g output/2024-05-27/16-55-10/)
